/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jatcsim.startup;

/**
 *
 * @author Marek Vajgl
 */
public class FrmWizardTraffic extends FrmWizardFrame {

  /**
   * Creates new form FrmWizardTraffic
   */
  public FrmWizardTraffic() {
    initComponents();
    initExtenders();

    grpRdb.add(rdbXml);
    grpRdb.add(rdbCustom);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    grpRdb = new javax.swing.ButtonGroup();
    rdbXml = new javax.swing.JRadioButton();
    pnlXml = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtTrafficXmlFile = new javax.swing.JTextField();
    btnTrafficXmlFileBrowse = new javax.swing.JButton();
    chkAllowDelays = new javax.swing.JCheckBox();
    rdbCustom = new javax.swing.JRadioButton();
    pnlCustom = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    nudMovements = new javax.swing.JSpinner();
    sldArrivalsDepartures = new javax.swing.JSlider();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    sldVfrIfr = new javax.swing.JSlider();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    sldA = new javax.swing.JSlider();
    sldB = new javax.swing.JSlider();
    sldC = new javax.swing.JSlider();
    sldD = new javax.swing.JSlider();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    btnContinue = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    rdbXml.setText("Use XML defined traffic");
    rdbXml.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdbXmlActionPerformed(evt);
      }
    });

    jLabel1.setText("Traffic XML file:");

    txtTrafficXmlFile.setText("---");

    btnTrafficXmlFileBrowse.setText("(browse)");

    chkAllowDelays.setText("Allow traffic delays");

    javax.swing.GroupLayout pnlXmlLayout = new javax.swing.GroupLayout(pnlXml);
    pnlXml.setLayout(pnlXmlLayout);
    pnlXmlLayout.setHorizontalGroup(
      pnlXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlXmlLayout.createSequentialGroup()
        .addGroup(pnlXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlXmlLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(chkAllowDelays, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(pnlXmlLayout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTrafficXmlFile)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnTrafficXmlFileBrowse)))
        .addContainerGap())
    );
    pnlXmlLayout.setVerticalGroup(
      pnlXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlXmlLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtTrafficXmlFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnTrafficXmlFileBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(chkAllowDelays)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    rdbCustom.setText("Use custom traffic");
    rdbCustom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdbCustomActionPerformed(evt);
      }
    });

    jLabel2.setText("Movements / hour:");

    nudMovements.setValue(10);
    nudMovements.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        nudMovementsStateChanged(evt);
      }
    });

    sldArrivalsDepartures.setMajorTickSpacing(1);
    sldArrivalsDepartures.setMaximum(10);
    sldArrivalsDepartures.setPaintTicks(true);
    sldArrivalsDepartures.setSnapToTicks(true);
    sldArrivalsDepartures.setValue(5);

    jLabel4.setText("Arrivals");

    jLabel5.setText("Departures");

    sldVfrIfr.setMajorTickSpacing(1);
    sldVfrIfr.setMaximum(10);
    sldVfrIfr.setPaintTicks(true);
    sldVfrIfr.setSnapToTicks(true);
    sldVfrIfr.setValue(5);

    jLabel3.setText("VFR");

    jLabel6.setText("IFR");

    sldA.setMajorTickSpacing(1);
    sldA.setMaximum(10);
    sldA.setPaintTicks(true);
    sldA.setSnapToTicks(true);
    sldA.setValue(5);

    sldB.setMajorTickSpacing(1);
    sldB.setMaximum(10);
    sldB.setPaintTicks(true);
    sldB.setSnapToTicks(true);
    sldB.setValue(5);

    sldC.setMajorTickSpacing(1);
    sldC.setMaximum(10);
    sldC.setPaintTicks(true);
    sldC.setSnapToTicks(true);
    sldC.setValue(5);

    sldD.setMajorTickSpacing(1);
    sldD.setMaximum(10);
    sldD.setPaintTicks(true);
    sldD.setSnapToTicks(true);
    sldD.setValue(5);

    jLabel7.setText("A plane type occurence probability weight");

    jLabel8.setText("B plane type occurence probability weight");

    jLabel9.setText("C plane type occurence probability weight");

    jLabel10.setText("D plane type occurence probability weight");

    javax.swing.GroupLayout pnlCustomLayout = new javax.swing.GroupLayout(pnlCustom);
    pnlCustom.setLayout(pnlCustomLayout);
    pnlCustomLayout.setHorizontalGroup(
      pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCustomLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlCustomLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(nudMovements, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(pnlCustomLayout.createSequentialGroup()
            .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel4)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pnlCustomLayout.createSequentialGroup()
                .addComponent(sldArrivalsDepartures, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
              .addGroup(pnlCustomLayout.createSequentialGroup()
                .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(sldA, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(sldVfrIfr, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(sldB, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(sldC, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(sldD, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel6)
                  .addComponent(jLabel7)
                  .addComponent(jLabel8)
                  .addComponent(jLabel9)
                  .addComponent(jLabel10))))))
        .addContainerGap(140, Short.MAX_VALUE))
    );
    pnlCustomLayout.setVerticalGroup(
      pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCustomLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(pnlCustomLayout.createSequentialGroup()
            .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(pnlCustomLayout.createSequentialGroup()
                .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(pnlCustomLayout.createSequentialGroup()
                    .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addGroup(pnlCustomLayout.createSequentialGroup()
                        .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jLabel2)
                          .addComponent(nudMovements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                          .addComponent(sldArrivalsDepartures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel4)))
                      .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(sldVfrIfr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(sldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnContinue.setText("Continue");
    btnContinue.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnContinueActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(rdbXml, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(rdbCustom))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(pnlXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnContinue)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(rdbXml)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rdbCustom)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlCustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnContinue)
        .addContainerGap(26, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void rdbXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbXmlActionPerformed
    updatePanelAccess();
  }//GEN-LAST:event_rdbXmlActionPerformed

  private void rdbCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCustomActionPerformed
    updatePanelAccess();
  }//GEN-LAST:event_rdbCustomActionPerformed

  private void nudMovementsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nudMovementsStateChanged
    int val = (int) nudMovements.getValue();
    if (val < 1) {
      nudMovements.setValue(1);
    }
  }//GEN-LAST:event_nudMovementsStateChanged

  private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
    super.closeDialogIfValid();
  }//GEN-LAST:event_btnContinueActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnContinue;
  private javax.swing.JButton btnTrafficXmlFileBrowse;
  private javax.swing.JCheckBox chkAllowDelays;
  private javax.swing.ButtonGroup grpRdb;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JSpinner nudMovements;
  private javax.swing.JPanel pnlCustom;
  private javax.swing.JPanel pnlXml;
  private javax.swing.JRadioButton rdbCustom;
  private javax.swing.JRadioButton rdbXml;
  private javax.swing.JSlider sldA;
  private javax.swing.JSlider sldArrivalsDepartures;
  private javax.swing.JSlider sldB;
  private javax.swing.JSlider sldC;
  private javax.swing.JSlider sldD;
  private javax.swing.JSlider sldVfrIfr;
  private javax.swing.JTextField txtTrafficXmlFile;
  // End of variables declaration//GEN-END:variables
XmlFileSelectorExtender xmlFile;

  @Override
  protected void fillBySettings() {

    rdbCustom.setSelected(settings.isTrafficUseXml() == false);
    rdbXml.setSelected(settings.isTrafficUseXml());
    chkAllowDelays.setSelected(settings.isTrafficXmlDelayAllowed());
    txtTrafficXmlFile.setText(settings.getTrafficXmlFile());
    nudMovements.setValue(settings.getTrafficCustomMovements());
    sldArrivalsDepartures.setValue(settings.getTrafficCustomArrivals2Departures());
    sldVfrIfr.setValue(settings.getTrafficCustomVfr2Ifr());
    sldA.setValue(settings.getTrafficCustomWeightTypeA());
    sldB.setValue(settings.getTrafficCustomWeightTypeB());
    sldC.setValue(settings.getTrafficCustomWeightTypeC());
    sldD.setValue(settings.getTrafficCustomWeightTypeD());

    updatePanelAccess();
  }

  @Override
  protected boolean isValidated() {

    if (rdbXml.isSelected()) {
      if (xmlFile.isValid() == false) {
        MessageBox.show("Xml file name is not valid.", "Error...");
        return false;
      }
    }

    settings.setTrafficUseXml(rdbXml.isSelected());
    settings.setTrafficXmlDelayAllowed(chkAllowDelays.isSelected());
    settings.setTrafficXmlFile(txtTrafficXmlFile.getText());
    settings.setTrafficCustomMovements((int) nudMovements.getValue());
    settings.setTrafficCustomArrivals2Departures(sldArrivalsDepartures.getValue());
    settings.setTrafficCustomVfr2Ifr(sldVfrIfr.getValue());
    settings.setTrafficCustomWeightTypeA(sldA.getValue());
    settings.setTrafficCustomWeightTypeB(sldB.getValue());
    settings.setTrafficCustomWeightTypeC(sldC.getValue());
    settings.setTrafficCustomWeightTypeD(sldD.getValue());

    return true;
  }

  private void initExtenders() {
    xmlFile = new XmlFileSelectorExtender(txtTrafficXmlFile, btnTrafficXmlFileBrowse);
  }

  private void updatePanelAccess() {
    pnlCustom.setEnabled(rdbCustom.isSelected());
    pnlXml.setEnabled(rdbXml.isSelected());
  }
}
