@startuml

title Relationships - Class Diagram

package "Piloting{
 class PilotOrders
 class Pilot
 class Behavior
 class Behavior
 class DivertableBehavior
 class BasicBehavior
 class DepartureBehavior
 class ArrivalBehavior
 class HoldBehavior
 class HoldingPointBehavior
 class TakeOffBehavior
 class ApproachBehavior
 package "ShaDriving"{
  class SHA
  class ShaDriver
  class ProceedToCoordinateShaDriver
  class FollowRadialShaDriver
  class FlyHeadingShaDriver
  class RunwayRollDriver
 }
}

class Airplane{
 callsign
 sqwk
 flight : Flight
 sha : SHA
 coordinate
 state
 flightRecorder
 pilot : Pilot
}

class Flight{
  callsign
  isDeparture
}


class SHA{
 speed
 targetSpeed
 heading
 targetHeading
 altitude
 targetAltitude
 lastVerticalSpeed
}

abstract class ShaDriver

class ProceedToCoordinateShaDriver{
  targetCoordinate
}
class FollowRadialShaDriver{
  fixCoordinate
  inboundRadial
}
class FlyHeadingShaDriver{
  targetHeading
}
class RunwayRollDriver







class Pilot{
 orders : PilotOrders
 saidText
 gaReason?
 divertInfo
 atc
 secondsWithoutRadarContact
 targetCoordinate
 behavior
 assignedRoute
 expectedRunwayThreshold
 entryExitPoint

 isAfterGoAround
}

class PilotOrders{
 speechQueue
 afterCommands
 altitudeOrderedByAtc
 speedRestriction
 altitudeRestriction
}

abstract class Behavior
abstract class DivertableBehavior
abstract class BasicBehavior
class DepartureBehavior
class ArrivalBehavior
class HoldBehavior
class HoldingPointBehavior
class TakeOffBehavior
class ApproachBehavior

Airplane "+" *-- "1" Pilot
Airplane "1" *-- "1" Flight

Behavior <|-- DivertableBehavior
Behavior <|-- ApproachBehavior
Behavior <|-- TakeOffBehavior
Behavior <|-- HoldingPointBehavior
DivertableBehavior <|-- HoldBehavior
DivertableBehavior <|-- BasicBehavior
BasicBehavior <|-- ArrivalBehavior
BasicBehavior <|-- DepartureBehavior


Pilot *-- ShaDriver
Pilot *-- Behavior
Pilot *-- PilotOrders
Pilot *-- SHA

ShaDriver <|-- ProceedToCoordinateShaDriver
ShaDriver <|-- FollowRadialShaDriver
ShaDriver <|-- FlyHeadingShaDriver
ShaDriver <|-- RunwayRollDriver

@enduml
