@startuml

title Components - Component Diagram

package Shared{
  [SharedLib (sl)] as sl
}

package "Base dependencies"{
  [AreaLib (al)] as al
  [AirplaneTypeLib (atl)] as atl
  [TrafficLib (tl)] as tl
  [FleetLib (fl)] as fl
  [WeatherLib (wl)] as wl
  [MessagingLib (ml)] as ml
  [MoodLib (mol)] as mol
  [StatsLib (stl)] as stl
}

package "Higher"{
  [AirplanesLib (pl)] as pl
}

package "Sim"{
  [SimulationLib (simlib)] as simlib
}

note top of stl : StatsManager and\nRecentStats should\nbe moved to SimulationLib

sl <-up- wl
sl <-up- al
sl <-up- atl
sl <-up- tl
sl <-up- ml
sl <-up- mol

atl <-up- pl

al <-up- pl

pl <-up-simlib

tl <-up- simlib

wl <-up- simlib

fl <-up- simlib

mol <-up- stl



@enduml
