@startuml
package "Shared"{
[SharedLib] as shared
}






package "Low-level"{
[FleetLib] as fleet
[MessagingLib] as messaging
[MoodLib] as mood
[TrafficLib] as traffic
[AirplaneTypeLib] as airplaneType
}

traffic -down-> shared
mood -down-> shared
messaging -down-> shared
fleet -down->shared





package "Midle-level"{
[StatsLib] as stats
[SpeechesLib] as speeches
}

stats -down-> mood
speeches -down-> messaging






package "Upper-level I"{
[AreaLib] as area
[TextProcessingLib] as textProcessing
}

textProcessing -down-> speeches
area -down-> speeches






package "Upper-level II"{
[WeatherLib] as weather
[AtcLib] as atc
[AirplanesLib] as airplanes
}

weather -down-> area
atc -down-> area
airplanes -down-> area
atc -down-> airplanes
atc -down-> weather
airplanes -down-> weather






package "Top-level"{
[SimulationLib] as simulation
}
simulation -down-> area
simulation -down-> atc
simulation -down-> textProcessing




textProcessing -> weather
@enduml
